# PATHS: change accordingly
wav_directory: '/data/datasets/LJSpeech-1.1' # path to wavs and metafile directory
metadata_path: '/data/datasets/LJSpeech-1.1/metadata.csv'  # name of metadata file under wav_directory
log_directory: '/data/francesco/logs/transformer_tts/main'   # weights and logs are stored here
train_data_directory: '/data/francesco/processed_datasets/transformer_tts_data'   # training data is stored here
data_config: 'config/data_config.yaml'
aligner_config: 'config/aligner_config.yaml'
tts_config: 'config/tts_config.yaml'

tts_config_name: tts_standard
aligner_config_name: aligner_bottleneck_PEmel_lowdiag
data_name: ljspeech # raw data naming for default data reader (select function from data/metadata_readers.py)