tts_config_name: tts_swapped_axis

# ARCHITECTURE
decoder_model_dimension: 384
encoder_model_dimension: 384
decoder_num_heads: [2, 2, 2, 2, 2, 2]  # the length of this defines the number of layers
encoder_num_heads: [2, 2, 2, 2, 2, 2]  # the length of this defines the number of layers
encoder_feed_forward_dimension: null
decoder_feed_forward_dimension: null
decoder_prenet_dimension: 384
encoder_prenet_dimension: 384
encoder_attention_conv_filters: [1536, 384]
decoder_attention_conv_filters: [1536, 384]
encoder_attention_conv_kernel: 3
decoder_attention_conv_kernel: 3
encoder_max_position_encoding: 2000
decoder_max_position_encoding: 10000
encoder_dense_blocks: 0
decoder_dense_blocks: 0
# STATS PREDICTORS ARCHITECTURE
duration_conv_filters: [256, 226]
pitch_conv_filters: [256, 226]
duration_kernel_size: 3
pitch_kernel_size: 3

# TRAINING
predictors_dropout: 0.1
dropout_rate: 0.1
learning_rate_schedule:
  - [0, 1.0e-4]
max_steps: 100_000
debug: False

# LOGGING
validation_frequency: 5_000
prediction_frequency: 5_000
weights_save_frequency: 5_000
weights_save_starting_step: 5_000
train_images_plotting_frequency: 1_000
keep_n_weights: 5
keep_checkpoint_every_n_hours: 12
n_steps_avg_losses: [100, 500, 1_000, 5_000]  # command line display of average loss values for the last n steps
prediction_start_step: 4_000
text_prediction:
  - test_sentences.txt