# PATHS: change accordingly
data_directory: '/path/to/dataset' # path to wavs and metafile directory
log_directory: '/path/to/logdir'   # weights and logs are stored here
metadata_filename: 'metadata.csv'  # name of metadata file under data_directory
train_metadata_filename: 'train_metafile.txt' # target file for training metadata
train_data_directory: 'transformer_tts_data'   # training data is stored here
valid_metadata_filename: 'valid_metafile.txt'
session_name: melgan    # session naming, can be specified in command line
data_name: ljspeech                # naming for default data reader (select function from preprocessing/metadata_readers.py)

# DATA
n_samples: 100000
n_test: 100
mel_start_value: .5
mel_end_value: -.5
max_mel_len: 1_200
min_mel_len: 80

# AUDIO
sampling_rate: 22050
n_fft: 1024
mel_channels: 80
hop_length: 256
win_length: 1024
f_min: 0
f_max: 8000
normalizer: MelGAN                 # which mel normalization to use from utils.audio.py [MelGAN or WaveRNN]
# TOKENIZER
phoneme_language: 'en-us'
with_stress: True                  # use stress symbols in phonemization
